### ISSUE TITLE
Upload to ESP32

### ISSUE THREAD

**Issue by ghost** [Pro/open62541-arduino#3]
So far everything worked great, the building process was flawless.
However I'm finding the server and client creation process a little bit cloudy.

There are some server/client examples at https://github.com/open62541/open62541/ , but I am struggling to translate it to a Arduino language, in order to upload to my ESP32.

I am not sure how and which files should be uploaded to my ESP32 (that has a Wifi Module). 

Do I need a platform manager like Platformio to upload it or should I upload the binary files?

Here are the built files:
![folders_build](https://user-images.githubusercontent.com/27338009/44226961-c4ddcc00-a191-11e8-9230-5f8d178ecc7a.png)

Any hint on with which one to start?

Thank you

**Comment by Pro** [comment]
I added additional explanation to the readme:

https://github.com/Pro/open62541-arduino/blob/master/README.md#how-to-flash

If that doesn't help, please reopen the issue.
